<?php
/**
 * Articletype
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Radix\Model;
use \OpenAPI\Client\Radix\ObjectSerializer;

/**
 * Articletype Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Articletype
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'None';

    public const COMMERCIAL_ARTICLE = 'CommercialArticle';

    public const PRODUCTION_ARTICLE = 'ProductionArticle';

    public const ARTICLE_TO_BE_ORDERED = 'ArticleToBeOrdered';

    public const SEMIFINISHED_PRODUCT = 'SemifinishedProduct';

    public const PRIMARY_PRODUCT = 'PrimaryProduct';

    public const FICTIVE_PART = 'FictivePart';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::COMMERCIAL_ARTICLE,
            self::PRODUCTION_ARTICLE,
            self::ARTICLE_TO_BE_ORDERED,
            self::SEMIFINISHED_PRODUCT,
            self::PRIMARY_PRODUCT,
            self::FICTIVE_PART
        ];
    }
}


