<?php
/**
 * CustomerShippingAddressPatchCommand
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Radix\Model;

use \ArrayAccess;
use \OpenAPI\Client\Radix\ObjectSerializer;

/**
 * CustomerShippingAddressPatchCommand Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerShippingAddressPatchCommand implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomerShippingAddressPatchCommand';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'defaultShippingAddress' => 'bool',
        'searchText' => 'string',
        'description' => 'string',
        'optional' => 'string',
        'salutation' => 'string',
        'letterSalutation' => 'string',
        'street' => 'string',
        'streetnumber' => 'string',
        'postalCode' => 'string',
        'town' => 'string',
        'province' => 'string',
        'country' => 'string',
        'phone' => '\OpenAPI\Client\Radix\Model\Phonenumber[]',
        'fax' => '\OpenAPI\Client\Radix\Model\Faxnumber[]',
        'email' => '\OpenAPI\Client\Radix\Model\Email[]',
        'emailPEC' => 'string',
        'url' => 'string',
        'language' => 'string',
        'isoVatnumber' => '\OpenAPI\Client\Radix\Model\IsoVatnumber',
        'taxnumber' => 'string',
        'note' => 'string',
        'mapLat' => 'float',
        'mapLong' => 'float',
        'taxGroupId' => 'string',
        'taxGroup' => 'string',
        'inactive' => 'bool',
        'lockedSince' => '\DateTime',
        'openingHours' => 'string',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'defaultShippingAddress' => null,
        'searchText' => null,
        'description' => null,
        'optional' => null,
        'salutation' => null,
        'letterSalutation' => null,
        'street' => null,
        'streetnumber' => null,
        'postalCode' => null,
        'town' => null,
        'province' => null,
        'country' => null,
        'phone' => null,
        'fax' => null,
        'email' => null,
        'emailPEC' => null,
        'url' => null,
        'language' => null,
        'isoVatnumber' => null,
        'taxnumber' => null,
        'note' => null,
        'mapLat' => 'double',
        'mapLong' => 'double',
        'taxGroupId' => null,
        'taxGroup' => null,
        'inactive' => null,
        'lockedSince' => 'date-time',
        'openingHours' => null,
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'defaultShippingAddress' => true,
        'searchText' => true,
        'description' => true,
        'optional' => true,
        'salutation' => true,
        'letterSalutation' => true,
        'street' => true,
        'streetnumber' => true,
        'postalCode' => true,
        'town' => true,
        'province' => true,
        'country' => true,
        'phone' => true,
        'fax' => true,
        'email' => true,
        'emailPEC' => true,
        'url' => true,
        'language' => true,
        'isoVatnumber' => false,
        'taxnumber' => true,
        'note' => true,
        'mapLat' => false,
        'mapLong' => false,
        'taxGroupId' => true,
        'taxGroup' => true,
        'inactive' => true,
        'lockedSince' => true,
        'openingHours' => true,
        'id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'defaultShippingAddress' => 'defaultShippingAddress',
        'searchText' => 'searchText',
        'description' => 'description',
        'optional' => 'optional',
        'salutation' => 'salutation',
        'letterSalutation' => 'letterSalutation',
        'street' => 'street',
        'streetnumber' => 'streetnumber',
        'postalCode' => 'postalCode',
        'town' => 'town',
        'province' => 'province',
        'country' => 'country',
        'phone' => 'phone',
        'fax' => 'fax',
        'email' => 'email',
        'emailPEC' => 'emailPEC',
        'url' => 'url',
        'language' => 'language',
        'isoVatnumber' => 'isoVatnumber',
        'taxnumber' => 'taxnumber',
        'note' => 'note',
        'mapLat' => 'mapLat',
        'mapLong' => 'mapLong',
        'taxGroupId' => 'taxGroupId',
        'taxGroup' => 'taxGroup',
        'inactive' => 'inactive',
        'lockedSince' => 'lockedSince',
        'openingHours' => 'openingHours',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'defaultShippingAddress' => 'setDefaultShippingAddress',
        'searchText' => 'setSearchText',
        'description' => 'setDescription',
        'optional' => 'setOptional',
        'salutation' => 'setSalutation',
        'letterSalutation' => 'setLetterSalutation',
        'street' => 'setStreet',
        'streetnumber' => 'setStreetnumber',
        'postalCode' => 'setPostalCode',
        'town' => 'setTown',
        'province' => 'setProvince',
        'country' => 'setCountry',
        'phone' => 'setPhone',
        'fax' => 'setFax',
        'email' => 'setEmail',
        'emailPEC' => 'setEmailPEC',
        'url' => 'setUrl',
        'language' => 'setLanguage',
        'isoVatnumber' => 'setIsoVatnumber',
        'taxnumber' => 'setTaxnumber',
        'note' => 'setNote',
        'mapLat' => 'setMapLat',
        'mapLong' => 'setMapLong',
        'taxGroupId' => 'setTaxGroupId',
        'taxGroup' => 'setTaxGroup',
        'inactive' => 'setInactive',
        'lockedSince' => 'setLockedSince',
        'openingHours' => 'setOpeningHours',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'defaultShippingAddress' => 'getDefaultShippingAddress',
        'searchText' => 'getSearchText',
        'description' => 'getDescription',
        'optional' => 'getOptional',
        'salutation' => 'getSalutation',
        'letterSalutation' => 'getLetterSalutation',
        'street' => 'getStreet',
        'streetnumber' => 'getStreetnumber',
        'postalCode' => 'getPostalCode',
        'town' => 'getTown',
        'province' => 'getProvince',
        'country' => 'getCountry',
        'phone' => 'getPhone',
        'fax' => 'getFax',
        'email' => 'getEmail',
        'emailPEC' => 'getEmailPEC',
        'url' => 'getUrl',
        'language' => 'getLanguage',
        'isoVatnumber' => 'getIsoVatnumber',
        'taxnumber' => 'getTaxnumber',
        'note' => 'getNote',
        'mapLat' => 'getMapLat',
        'mapLong' => 'getMapLong',
        'taxGroupId' => 'getTaxGroupId',
        'taxGroup' => 'getTaxGroup',
        'inactive' => 'getInactive',
        'lockedSince' => 'getLockedSince',
        'openingHours' => 'getOpeningHours',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('defaultShippingAddress', $data ?? [], null);
        $this->setIfExists('searchText', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('optional', $data ?? [], null);
        $this->setIfExists('salutation', $data ?? [], null);
        $this->setIfExists('letterSalutation', $data ?? [], null);
        $this->setIfExists('street', $data ?? [], null);
        $this->setIfExists('streetnumber', $data ?? [], null);
        $this->setIfExists('postalCode', $data ?? [], null);
        $this->setIfExists('town', $data ?? [], null);
        $this->setIfExists('province', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('fax', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('emailPEC', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('isoVatnumber', $data ?? [], null);
        $this->setIfExists('taxnumber', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('mapLat', $data ?? [], null);
        $this->setIfExists('mapLong', $data ?? [], null);
        $this->setIfExists('taxGroupId', $data ?? [], null);
        $this->setIfExists('taxGroup', $data ?? [], null);
        $this->setIfExists('inactive', $data ?? [], null);
        $this->setIfExists('lockedSince', $data ?? [], null);
        $this->setIfExists('openingHours', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets defaultShippingAddress
     *
     * @return bool|null
     */
    public function getDefaultShippingAddress()
    {
        return $this->container['defaultShippingAddress'];
    }

    /**
     * Sets defaultShippingAddress
     *
     * @param bool|null $defaultShippingAddress defaultShippingAddress
     *
     * @return self
     */
    public function setDefaultShippingAddress($defaultShippingAddress)
    {
        if (is_null($defaultShippingAddress)) {
            array_push($this->openAPINullablesSetToNull, 'defaultShippingAddress');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('defaultShippingAddress', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['defaultShippingAddress'] = $defaultShippingAddress;

        return $this;
    }

    /**
     * Gets searchText
     *
     * @return string|null
     */
    public function getSearchText()
    {
        return $this->container['searchText'];
    }

    /**
     * Sets searchText
     *
     * @param string|null $searchText searchText
     *
     * @return self
     */
    public function setSearchText($searchText)
    {
        if (is_null($searchText)) {
            array_push($this->openAPINullablesSetToNull, 'searchText');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('searchText', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['searchText'] = $searchText;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets optional
     *
     * @return string|null
     */
    public function getOptional()
    {
        return $this->container['optional'];
    }

    /**
     * Sets optional
     *
     * @param string|null $optional optional
     *
     * @return self
     */
    public function setOptional($optional)
    {
        if (is_null($optional)) {
            array_push($this->openAPINullablesSetToNull, 'optional');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('optional', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['optional'] = $optional;

        return $this;
    }

    /**
     * Gets salutation
     *
     * @return string|null
     */
    public function getSalutation()
    {
        return $this->container['salutation'];
    }

    /**
     * Sets salutation
     *
     * @param string|null $salutation salutation
     *
     * @return self
     */
    public function setSalutation($salutation)
    {
        if (is_null($salutation)) {
            array_push($this->openAPINullablesSetToNull, 'salutation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('salutation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['salutation'] = $salutation;

        return $this;
    }

    /**
     * Gets letterSalutation
     *
     * @return string|null
     */
    public function getLetterSalutation()
    {
        return $this->container['letterSalutation'];
    }

    /**
     * Sets letterSalutation
     *
     * @param string|null $letterSalutation letterSalutation
     *
     * @return self
     */
    public function setLetterSalutation($letterSalutation)
    {
        if (is_null($letterSalutation)) {
            array_push($this->openAPINullablesSetToNull, 'letterSalutation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('letterSalutation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['letterSalutation'] = $letterSalutation;

        return $this;
    }

    /**
     * Gets street
     *
     * @return string|null
     */
    public function getStreet()
    {
        return $this->container['street'];
    }

    /**
     * Sets street
     *
     * @param string|null $street street
     *
     * @return self
     */
    public function setStreet($street)
    {
        if (is_null($street)) {
            array_push($this->openAPINullablesSetToNull, 'street');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('street', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['street'] = $street;

        return $this;
    }

    /**
     * Gets streetnumber
     *
     * @return string|null
     */
    public function getStreetnumber()
    {
        return $this->container['streetnumber'];
    }

    /**
     * Sets streetnumber
     *
     * @param string|null $streetnumber streetnumber
     *
     * @return self
     */
    public function setStreetnumber($streetnumber)
    {
        if (is_null($streetnumber)) {
            array_push($this->openAPINullablesSetToNull, 'streetnumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('streetnumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['streetnumber'] = $streetnumber;

        return $this;
    }

    /**
     * Gets postalCode
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     *
     * @param string|null $postalCode postalCode
     *
     * @return self
     */
    public function setPostalCode($postalCode)
    {
        if (is_null($postalCode)) {
            array_push($this->openAPINullablesSetToNull, 'postalCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('postalCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets town
     *
     * @return string|null
     */
    public function getTown()
    {
        return $this->container['town'];
    }

    /**
     * Sets town
     *
     * @param string|null $town town
     *
     * @return self
     */
    public function setTown($town)
    {
        if (is_null($town)) {
            array_push($this->openAPINullablesSetToNull, 'town');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('town', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['town'] = $town;

        return $this;
    }

    /**
     * Gets province
     *
     * @return string|null
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     *
     * @param string|null $province province
     *
     * @return self
     */
    public function setProvince($province)
    {
        if (is_null($province)) {
            array_push($this->openAPINullablesSetToNull, 'province');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('province', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return \OpenAPI\Client\Radix\Model\Phonenumber[]|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param \OpenAPI\Client\Radix\Model\Phonenumber[]|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return \OpenAPI\Client\Radix\Model\Faxnumber[]|null
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param \OpenAPI\Client\Radix\Model\Faxnumber[]|null $fax fax
     *
     * @return self
     */
    public function setFax($fax)
    {
        if (is_null($fax)) {
            array_push($this->openAPINullablesSetToNull, 'fax');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fax', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets email
     *
     * @return \OpenAPI\Client\Radix\Model\Email[]|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param \OpenAPI\Client\Radix\Model\Email[]|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets emailPEC
     *
     * @return string|null
     */
    public function getEmailPEC()
    {
        return $this->container['emailPEC'];
    }

    /**
     * Sets emailPEC
     *
     * @param string|null $emailPEC emailPEC
     *
     * @return self
     */
    public function setEmailPEC($emailPEC)
    {
        if (is_null($emailPEC)) {
            array_push($this->openAPINullablesSetToNull, 'emailPEC');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('emailPEC', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['emailPEC'] = $emailPEC;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            array_push($this->openAPINullablesSetToNull, 'language');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('language', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets isoVatnumber
     *
     * @return \OpenAPI\Client\Radix\Model\IsoVatnumber|null
     */
    public function getIsoVatnumber()
    {
        return $this->container['isoVatnumber'];
    }

    /**
     * Sets isoVatnumber
     *
     * @param \OpenAPI\Client\Radix\Model\IsoVatnumber|null $isoVatnumber isoVatnumber
     *
     * @return self
     */
    public function setIsoVatnumber($isoVatnumber)
    {
        if (is_null($isoVatnumber)) {
            throw new \InvalidArgumentException('non-nullable isoVatnumber cannot be null');
        }
        $this->container['isoVatnumber'] = $isoVatnumber;

        return $this;
    }

    /**
     * Gets taxnumber
     *
     * @return string|null
     */
    public function getTaxnumber()
    {
        return $this->container['taxnumber'];
    }

    /**
     * Sets taxnumber
     *
     * @param string|null $taxnumber taxnumber
     *
     * @return self
     */
    public function setTaxnumber($taxnumber)
    {
        if (is_null($taxnumber)) {
            array_push($this->openAPINullablesSetToNull, 'taxnumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taxnumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taxnumber'] = $taxnumber;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            array_push($this->openAPINullablesSetToNull, 'note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets mapLat
     *
     * @return float|null
     */
    public function getMapLat()
    {
        return $this->container['mapLat'];
    }

    /**
     * Sets mapLat
     *
     * @param float|null $mapLat mapLat
     *
     * @return self
     */
    public function setMapLat($mapLat)
    {
        if (is_null($mapLat)) {
            throw new \InvalidArgumentException('non-nullable mapLat cannot be null');
        }
        $this->container['mapLat'] = $mapLat;

        return $this;
    }

    /**
     * Gets mapLong
     *
     * @return float|null
     */
    public function getMapLong()
    {
        return $this->container['mapLong'];
    }

    /**
     * Sets mapLong
     *
     * @param float|null $mapLong mapLong
     *
     * @return self
     */
    public function setMapLong($mapLong)
    {
        if (is_null($mapLong)) {
            throw new \InvalidArgumentException('non-nullable mapLong cannot be null');
        }
        $this->container['mapLong'] = $mapLong;

        return $this;
    }

    /**
     * Gets taxGroupId
     *
     * @return string|null
     */
    public function getTaxGroupId()
    {
        return $this->container['taxGroupId'];
    }

    /**
     * Sets taxGroupId
     *
     * @param string|null $taxGroupId taxGroupId
     *
     * @return self
     */
    public function setTaxGroupId($taxGroupId)
    {
        if (is_null($taxGroupId)) {
            array_push($this->openAPINullablesSetToNull, 'taxGroupId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taxGroupId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taxGroupId'] = $taxGroupId;

        return $this;
    }

    /**
     * Gets taxGroup
     *
     * @return string|null
     */
    public function getTaxGroup()
    {
        return $this->container['taxGroup'];
    }

    /**
     * Sets taxGroup
     *
     * @param string|null $taxGroup taxGroup
     *
     * @return self
     */
    public function setTaxGroup($taxGroup)
    {
        if (is_null($taxGroup)) {
            array_push($this->openAPINullablesSetToNull, 'taxGroup');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('taxGroup', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['taxGroup'] = $taxGroup;

        return $this;
    }

    /**
     * Gets inactive
     *
     * @return bool|null
     */
    public function getInactive()
    {
        return $this->container['inactive'];
    }

    /**
     * Sets inactive
     *
     * @param bool|null $inactive inactive
     *
     * @return self
     */
    public function setInactive($inactive)
    {
        if (is_null($inactive)) {
            array_push($this->openAPINullablesSetToNull, 'inactive');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('inactive', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['inactive'] = $inactive;

        return $this;
    }

    /**
     * Gets lockedSince
     *
     * @return \DateTime|null
     */
    public function getLockedSince()
    {
        return $this->container['lockedSince'];
    }

    /**
     * Sets lockedSince
     *
     * @param \DateTime|null $lockedSince lockedSince
     *
     * @return self
     */
    public function setLockedSince($lockedSince)
    {
        if (is_null($lockedSince)) {
            array_push($this->openAPINullablesSetToNull, 'lockedSince');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lockedSince', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lockedSince'] = $lockedSince;

        return $this;
    }

    /**
     * Gets openingHours
     *
     * @return string|null
     */
    public function getOpeningHours()
    {
        return $this->container['openingHours'];
    }

    /**
     * Sets openingHours
     *
     * @param string|null $openingHours openingHours
     *
     * @return self
     */
    public function setOpeningHours($openingHours)
    {
        if (is_null($openingHours)) {
            array_push($this->openAPINullablesSetToNull, 'openingHours');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('openingHours', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['openingHours'] = $openingHours;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


