<?php
/**
 * Emailtyp
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Radix\Model;
use \OpenAPI\Client\Radix\ObjectSerializer;

/**
 * Emailtyp Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Emailtyp
{
    /**
     * Possible values of this enum
     */
    public const EMAIL = 'Email';

    public const EMAIL2 = 'Email2';

    public const EMAIL3 = 'Email3';

    public const EMAIL4 = 'Email4';

    public const EMAIL5 = 'Email5';

    public const EMAIL6 = 'Email6';

    public const EMAIL7 = 'Email7';

    public const EMAIL8 = 'Email8';

    public const EMAIL9 = 'Email9';

    public const EMAIL10 = 'Email10';

    public const EMAIL11 = 'Email11';

    public const EMAIL12 = 'Email12';

    public const EMAIL13 = 'Email13';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMAIL,
            self::EMAIL2,
            self::EMAIL3,
            self::EMAIL4,
            self::EMAIL5,
            self::EMAIL6,
            self::EMAIL7,
            self::EMAIL8,
            self::EMAIL9,
            self::EMAIL10,
            self::EMAIL11,
            self::EMAIL12,
            self::EMAIL13
        ];
    }
}


