<?php
/**
 * Faxnumbertyp
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Radix\Model;
use \OpenAPI\Client\Radix\ObjectSerializer;

/**
 * Faxnumbertyp Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Faxnumbertyp
{
    /**
     * Possible values of this enum
     */
    public const BUSINESS = 'Business';

    public const ADDIONAL = 'Addional';

    public const FAX3 = 'Fax3';

    public const FAX4 = 'Fax4';

    public const FAX5 = 'Fax5';

    public const FAX6 = 'Fax6';

    public const FAX7 = 'Fax7';

    public const FAX8 = 'Fax8';

    public const FAX9 = 'Fax9';

    public const FAX10 = 'Fax10';

    public const FAX11 = 'Fax11';

    public const FAX12 = 'Fax12';

    public const FAX13 = 'Fax13';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUSINESS,
            self::ADDIONAL,
            self::FAX3,
            self::FAX4,
            self::FAX5,
            self::FAX6,
            self::FAX7,
            self::FAX8,
            self::FAX9,
            self::FAX10,
            self::FAX11,
            self::FAX12,
            self::FAX13
        ];
    }
}


