<?php
/**
 * PriceDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Radix\Model;

use \ArrayAccess;
use \OpenAPI\Client\Radix\ObjectSerializer;

/**
 * PriceDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PriceDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PriceDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'articleId' => 'string',
        'customerId' => 'string',
        'supplierId' => 'string',
        'promotionId' => 'string',
        'currency' => 'string',
        'companyId' => 'string',
        'priceKey' => 'string',
        'validFrom' => '\DateTime',
        'validUntil' => '\DateTime',
        'amount' => 'float',
        'discount1' => 'float',
        'discount2' => 'float',
        'discount3' => 'float',
        'discount4' => 'float',
        'discount5' => 'float',
        'fromQuantity' => 'float',
        'surchargeDebit' => 'float',
        'unit' => 'int',
        'rounding' => 'float',
        'option1' => 'string',
        'option1Logic' => 'bool',
        'option1Date' => '\DateTime',
        'dependancyType' => '\OpenAPI\Client\Radix\Model\PriceDependancytype',
        'dependancyPriceKey' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'articleId' => null,
        'customerId' => null,
        'supplierId' => null,
        'promotionId' => null,
        'currency' => null,
        'companyId' => null,
        'priceKey' => null,
        'validFrom' => 'date-time',
        'validUntil' => 'date-time',
        'amount' => 'double',
        'discount1' => 'double',
        'discount2' => 'double',
        'discount3' => 'double',
        'discount4' => 'double',
        'discount5' => 'double',
        'fromQuantity' => 'double',
        'surchargeDebit' => 'double',
        'unit' => 'int32',
        'rounding' => 'double',
        'option1' => null,
        'option1Logic' => null,
        'option1Date' => 'date-time',
        'dependancyType' => null,
        'dependancyPriceKey' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'articleId' => true,
        'customerId' => true,
        'supplierId' => true,
        'promotionId' => true,
        'currency' => true,
        'companyId' => true,
        'priceKey' => true,
        'validFrom' => false,
        'validUntil' => false,
        'amount' => false,
        'discount1' => false,
        'discount2' => false,
        'discount3' => false,
        'discount4' => true,
        'discount5' => true,
        'fromQuantity' => false,
        'surchargeDebit' => false,
        'unit' => false,
        'rounding' => false,
        'option1' => true,
        'option1Logic' => true,
        'option1Date' => true,
        'dependancyType' => false,
        'dependancyPriceKey' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'articleId' => 'articleId',
        'customerId' => 'customerId',
        'supplierId' => 'supplierId',
        'promotionId' => 'promotionId',
        'currency' => 'currency',
        'companyId' => 'companyId',
        'priceKey' => 'priceKey',
        'validFrom' => 'validFrom',
        'validUntil' => 'validUntil',
        'amount' => 'amount',
        'discount1' => 'discount1',
        'discount2' => 'discount2',
        'discount3' => 'discount3',
        'discount4' => 'discount4',
        'discount5' => 'discount5',
        'fromQuantity' => 'fromQuantity',
        'surchargeDebit' => 'surchargeDebit',
        'unit' => 'unit',
        'rounding' => 'rounding',
        'option1' => 'option1',
        'option1Logic' => 'option1Logic',
        'option1Date' => 'option1Date',
        'dependancyType' => 'dependancyType',
        'dependancyPriceKey' => 'dependancyPriceKey'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'articleId' => 'setArticleId',
        'customerId' => 'setCustomerId',
        'supplierId' => 'setSupplierId',
        'promotionId' => 'setPromotionId',
        'currency' => 'setCurrency',
        'companyId' => 'setCompanyId',
        'priceKey' => 'setPriceKey',
        'validFrom' => 'setValidFrom',
        'validUntil' => 'setValidUntil',
        'amount' => 'setAmount',
        'discount1' => 'setDiscount1',
        'discount2' => 'setDiscount2',
        'discount3' => 'setDiscount3',
        'discount4' => 'setDiscount4',
        'discount5' => 'setDiscount5',
        'fromQuantity' => 'setFromQuantity',
        'surchargeDebit' => 'setSurchargeDebit',
        'unit' => 'setUnit',
        'rounding' => 'setRounding',
        'option1' => 'setOption1',
        'option1Logic' => 'setOption1Logic',
        'option1Date' => 'setOption1Date',
        'dependancyType' => 'setDependancyType',
        'dependancyPriceKey' => 'setDependancyPriceKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'articleId' => 'getArticleId',
        'customerId' => 'getCustomerId',
        'supplierId' => 'getSupplierId',
        'promotionId' => 'getPromotionId',
        'currency' => 'getCurrency',
        'companyId' => 'getCompanyId',
        'priceKey' => 'getPriceKey',
        'validFrom' => 'getValidFrom',
        'validUntil' => 'getValidUntil',
        'amount' => 'getAmount',
        'discount1' => 'getDiscount1',
        'discount2' => 'getDiscount2',
        'discount3' => 'getDiscount3',
        'discount4' => 'getDiscount4',
        'discount5' => 'getDiscount5',
        'fromQuantity' => 'getFromQuantity',
        'surchargeDebit' => 'getSurchargeDebit',
        'unit' => 'getUnit',
        'rounding' => 'getRounding',
        'option1' => 'getOption1',
        'option1Logic' => 'getOption1Logic',
        'option1Date' => 'getOption1Date',
        'dependancyType' => 'getDependancyType',
        'dependancyPriceKey' => 'getDependancyPriceKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('articleId', $data ?? [], null);
        $this->setIfExists('customerId', $data ?? [], null);
        $this->setIfExists('supplierId', $data ?? [], null);
        $this->setIfExists('promotionId', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('companyId', $data ?? [], null);
        $this->setIfExists('priceKey', $data ?? [], null);
        $this->setIfExists('validFrom', $data ?? [], null);
        $this->setIfExists('validUntil', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('discount1', $data ?? [], null);
        $this->setIfExists('discount2', $data ?? [], null);
        $this->setIfExists('discount3', $data ?? [], null);
        $this->setIfExists('discount4', $data ?? [], null);
        $this->setIfExists('discount5', $data ?? [], null);
        $this->setIfExists('fromQuantity', $data ?? [], null);
        $this->setIfExists('surchargeDebit', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
        $this->setIfExists('rounding', $data ?? [], null);
        $this->setIfExists('option1', $data ?? [], null);
        $this->setIfExists('option1Logic', $data ?? [], null);
        $this->setIfExists('option1Date', $data ?? [], null);
        $this->setIfExists('dependancyType', $data ?? [], null);
        $this->setIfExists('dependancyPriceKey', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets articleId
     *
     * @return string|null
     */
    public function getArticleId()
    {
        return $this->container['articleId'];
    }

    /**
     * Sets articleId
     *
     * @param string|null $articleId articleId
     *
     * @return self
     */
    public function setArticleId($articleId)
    {
        if (is_null($articleId)) {
            array_push($this->openAPINullablesSetToNull, 'articleId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('articleId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['articleId'] = $articleId;

        return $this;
    }

    /**
     * Gets customerId
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string|null $customerId customerId
     *
     * @return self
     */
    public function setCustomerId($customerId)
    {
        if (is_null($customerId)) {
            array_push($this->openAPINullablesSetToNull, 'customerId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customerId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets supplierId
     *
     * @return string|null
     */
    public function getSupplierId()
    {
        return $this->container['supplierId'];
    }

    /**
     * Sets supplierId
     *
     * @param string|null $supplierId supplierId
     *
     * @return self
     */
    public function setSupplierId($supplierId)
    {
        if (is_null($supplierId)) {
            array_push($this->openAPINullablesSetToNull, 'supplierId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('supplierId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['supplierId'] = $supplierId;

        return $this;
    }

    /**
     * Gets promotionId
     *
     * @return string|null
     */
    public function getPromotionId()
    {
        return $this->container['promotionId'];
    }

    /**
     * Sets promotionId
     *
     * @param string|null $promotionId promotionId
     *
     * @return self
     */
    public function setPromotionId($promotionId)
    {
        if (is_null($promotionId)) {
            array_push($this->openAPINullablesSetToNull, 'promotionId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('promotionId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['promotionId'] = $promotionId;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            array_push($this->openAPINullablesSetToNull, 'currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets companyId
     *
     * @return string|null
     */
    public function getCompanyId()
    {
        return $this->container['companyId'];
    }

    /**
     * Sets companyId
     *
     * @param string|null $companyId companyId
     *
     * @return self
     */
    public function setCompanyId($companyId)
    {
        if (is_null($companyId)) {
            array_push($this->openAPINullablesSetToNull, 'companyId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('companyId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['companyId'] = $companyId;

        return $this;
    }

    /**
     * Gets priceKey
     *
     * @return string|null
     */
    public function getPriceKey()
    {
        return $this->container['priceKey'];
    }

    /**
     * Sets priceKey
     *
     * @param string|null $priceKey priceKey
     *
     * @return self
     */
    public function setPriceKey($priceKey)
    {
        if (is_null($priceKey)) {
            array_push($this->openAPINullablesSetToNull, 'priceKey');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('priceKey', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['priceKey'] = $priceKey;

        return $this;
    }

    /**
     * Gets validFrom
     *
     * @return \DateTime|null
     */
    public function getValidFrom()
    {
        return $this->container['validFrom'];
    }

    /**
     * Sets validFrom
     *
     * @param \DateTime|null $validFrom validFrom
     *
     * @return self
     */
    public function setValidFrom($validFrom)
    {
        if (is_null($validFrom)) {
            throw new \InvalidArgumentException('non-nullable validFrom cannot be null');
        }
        $this->container['validFrom'] = $validFrom;

        return $this;
    }

    /**
     * Gets validUntil
     *
     * @return \DateTime|null
     */
    public function getValidUntil()
    {
        return $this->container['validUntil'];
    }

    /**
     * Sets validUntil
     *
     * @param \DateTime|null $validUntil validUntil
     *
     * @return self
     */
    public function setValidUntil($validUntil)
    {
        if (is_null($validUntil)) {
            throw new \InvalidArgumentException('non-nullable validUntil cannot be null');
        }
        $this->container['validUntil'] = $validUntil;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets discount1
     *
     * @return float|null
     */
    public function getDiscount1()
    {
        return $this->container['discount1'];
    }

    /**
     * Sets discount1
     *
     * @param float|null $discount1 discount1
     *
     * @return self
     */
    public function setDiscount1($discount1)
    {
        if (is_null($discount1)) {
            throw new \InvalidArgumentException('non-nullable discount1 cannot be null');
        }
        $this->container['discount1'] = $discount1;

        return $this;
    }

    /**
     * Gets discount2
     *
     * @return float|null
     */
    public function getDiscount2()
    {
        return $this->container['discount2'];
    }

    /**
     * Sets discount2
     *
     * @param float|null $discount2 discount2
     *
     * @return self
     */
    public function setDiscount2($discount2)
    {
        if (is_null($discount2)) {
            throw new \InvalidArgumentException('non-nullable discount2 cannot be null');
        }
        $this->container['discount2'] = $discount2;

        return $this;
    }

    /**
     * Gets discount3
     *
     * @return float|null
     */
    public function getDiscount3()
    {
        return $this->container['discount3'];
    }

    /**
     * Sets discount3
     *
     * @param float|null $discount3 discount3
     *
     * @return self
     */
    public function setDiscount3($discount3)
    {
        if (is_null($discount3)) {
            throw new \InvalidArgumentException('non-nullable discount3 cannot be null');
        }
        $this->container['discount3'] = $discount3;

        return $this;
    }

    /**
     * Gets discount4
     *
     * @return float|null
     */
    public function getDiscount4()
    {
        return $this->container['discount4'];
    }

    /**
     * Sets discount4
     *
     * @param float|null $discount4 discount4
     *
     * @return self
     */
    public function setDiscount4($discount4)
    {
        if (is_null($discount4)) {
            array_push($this->openAPINullablesSetToNull, 'discount4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discount4'] = $discount4;

        return $this;
    }

    /**
     * Gets discount5
     *
     * @return float|null
     */
    public function getDiscount5()
    {
        return $this->container['discount5'];
    }

    /**
     * Sets discount5
     *
     * @param float|null $discount5 discount5
     *
     * @return self
     */
    public function setDiscount5($discount5)
    {
        if (is_null($discount5)) {
            array_push($this->openAPINullablesSetToNull, 'discount5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discount5'] = $discount5;

        return $this;
    }

    /**
     * Gets fromQuantity
     *
     * @return float|null
     */
    public function getFromQuantity()
    {
        return $this->container['fromQuantity'];
    }

    /**
     * Sets fromQuantity
     *
     * @param float|null $fromQuantity fromQuantity
     *
     * @return self
     */
    public function setFromQuantity($fromQuantity)
    {
        if (is_null($fromQuantity)) {
            throw new \InvalidArgumentException('non-nullable fromQuantity cannot be null');
        }
        $this->container['fromQuantity'] = $fromQuantity;

        return $this;
    }

    /**
     * Gets surchargeDebit
     *
     * @return float|null
     */
    public function getSurchargeDebit()
    {
        return $this->container['surchargeDebit'];
    }

    /**
     * Sets surchargeDebit
     *
     * @param float|null $surchargeDebit surchargeDebit
     *
     * @return self
     */
    public function setSurchargeDebit($surchargeDebit)
    {
        if (is_null($surchargeDebit)) {
            throw new \InvalidArgumentException('non-nullable surchargeDebit cannot be null');
        }
        $this->container['surchargeDebit'] = $surchargeDebit;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return int|null
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param int|null $unit unit
     *
     * @return self
     */
    public function setUnit($unit)
    {
        if (is_null($unit)) {
            throw new \InvalidArgumentException('non-nullable unit cannot be null');
        }
        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets rounding
     *
     * @return float|null
     */
    public function getRounding()
    {
        return $this->container['rounding'];
    }

    /**
     * Sets rounding
     *
     * @param float|null $rounding rounding
     *
     * @return self
     */
    public function setRounding($rounding)
    {
        if (is_null($rounding)) {
            throw new \InvalidArgumentException('non-nullable rounding cannot be null');
        }
        $this->container['rounding'] = $rounding;

        return $this;
    }

    /**
     * Gets option1
     *
     * @return string|null
     */
    public function getOption1()
    {
        return $this->container['option1'];
    }

    /**
     * Sets option1
     *
     * @param string|null $option1 option1
     *
     * @return self
     */
    public function setOption1($option1)
    {
        if (is_null($option1)) {
            array_push($this->openAPINullablesSetToNull, 'option1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('option1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['option1'] = $option1;

        return $this;
    }

    /**
     * Gets option1Logic
     *
     * @return bool|null
     */
    public function getOption1Logic()
    {
        return $this->container['option1Logic'];
    }

    /**
     * Sets option1Logic
     *
     * @param bool|null $option1Logic option1Logic
     *
     * @return self
     */
    public function setOption1Logic($option1Logic)
    {
        if (is_null($option1Logic)) {
            array_push($this->openAPINullablesSetToNull, 'option1Logic');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('option1Logic', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['option1Logic'] = $option1Logic;

        return $this;
    }

    /**
     * Gets option1Date
     *
     * @return \DateTime|null
     */
    public function getOption1Date()
    {
        return $this->container['option1Date'];
    }

    /**
     * Sets option1Date
     *
     * @param \DateTime|null $option1Date option1Date
     *
     * @return self
     */
    public function setOption1Date($option1Date)
    {
        if (is_null($option1Date)) {
            array_push($this->openAPINullablesSetToNull, 'option1Date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('option1Date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['option1Date'] = $option1Date;

        return $this;
    }

    /**
     * Gets dependancyType
     *
     * @return \OpenAPI\Client\Radix\Model\PriceDependancytype|null
     */
    public function getDependancyType()
    {
        return $this->container['dependancyType'];
    }

    /**
     * Sets dependancyType
     *
     * @param \OpenAPI\Client\Radix\Model\PriceDependancytype|null $dependancyType dependancyType
     *
     * @return self
     */
    public function setDependancyType($dependancyType)
    {
        if (is_null($dependancyType)) {
            throw new \InvalidArgumentException('non-nullable dependancyType cannot be null');
        }
        $this->container['dependancyType'] = $dependancyType;

        return $this;
    }

    /**
     * Gets dependancyPriceKey
     *
     * @return string|null
     */
    public function getDependancyPriceKey()
    {
        return $this->container['dependancyPriceKey'];
    }

    /**
     * Sets dependancyPriceKey
     *
     * @param string|null $dependancyPriceKey dependancyPriceKey
     *
     * @return self
     */
    public function setDependancyPriceKey($dependancyPriceKey)
    {
        if (is_null($dependancyPriceKey)) {
            array_push($this->openAPINullablesSetToNull, 'dependancyPriceKey');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dependancyPriceKey', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dependancyPriceKey'] = $dependancyPriceKey;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


