<?php
/**
 * CommonApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Radix\Test\Api;

use \OpenAPI\Client\Radix\Configuration;
use \OpenAPI\Client\Radix\ApiException;
use \OpenAPI\Client\Radix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CommonApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommonApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1CommonClassificationDefinitionGet
     *
     * Returns the classificationdefinitions.
     *
     */
    public function testApiV1CommonClassificationDefinitionGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonClassificationDefinitionValueGet
     *
     * Returns the values of classificationdefinitions.
     *
     */
    public function testApiV1CommonClassificationDefinitionValueGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonClassificationsGet
     *
     * Returns the classifications.
     *
     */
    public function testApiV1CommonClassificationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonClassificationsPatch
     *
     * Update a list of classifications.
     *
     */
    public function testApiV1CommonClassificationsPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonClassificationsPost
     *
     * Creating a list of classifications.
     *
     */
    public function testApiV1CommonClassificationsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonMessagesGet
     *
     * Returns the messages.
     *
     */
    public function testApiV1CommonMessagesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonTipDelete
     *
     * delete a tip.
     *
     */
    public function testApiV1CommonTipDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonTipPatch
     *
     * update a tip.
     *
     */
    public function testApiV1CommonTipPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonTipPost
     *
     * Creating a tip.
     *
     */
    public function testApiV1CommonTipPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CommonTipsGet
     *
     * Returns the tips.
     *
     */
    public function testApiV1CommonTipsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
