<?php
/**
 * CustomerShippingAddressesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Radix\Test\Api;

use \OpenAPI\Client\Radix\Configuration;
use \OpenAPI\Client\Radix\ApiException;
use \OpenAPI\Client\Radix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerShippingAddressesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerShippingAddressesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1CustomerShippingAddressesCountGet
     *
     * Returns the count of customer-shippingaddresses.
     *
     */
    public function testApiV1CustomerShippingAddressesCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesDelete
     *
     * Delete an customer-shippingaddress.
     *
     */
    public function testApiV1CustomerShippingAddressesDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesGet
     *
     * Returns a list of customer-shippingaddresses.
     *
     */
    public function testApiV1CustomerShippingAddressesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesIdIdGet
     *
     * Returns the customer-shippingaddress with this ID.
     *
     */
    public function testApiV1CustomerShippingAddressesIdIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesListGet
     *
     * Returns a list of customer-shippingaddresses with minimal data.
     *
     */
    public function testApiV1CustomerShippingAddressesListGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesPatch
     *
     * Updating an customer-shippingaddress.
     *
     */
    public function testApiV1CustomerShippingAddressesPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1CustomerShippingAddressesPost
     *
     * Creating an customer-shippingaddress.
     *
     */
    public function testApiV1CustomerShippingAddressesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
