<?php
/**
 * OrdersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Radix\Test\Api;

use \OpenAPI\Client\Radix\Configuration;
use \OpenAPI\Client\Radix\ApiException;
use \OpenAPI\Client\Radix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrdersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1OrdersCountGet
     *
     * Returns the count of orders.
     *
     */
    public function testApiV1OrdersCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersDelete
     *
     * Delete an Order.
     *
     */
    public function testApiV1OrdersDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersGet
     *
     * Returns a list of orders.
     *
     */
    public function testApiV1OrdersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersIdIdGet
     *
     * Returns the order with this ID.
     *
     */
    public function testApiV1OrdersIdIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersListGet
     *
     * Returns a list of orders with minimal data.
     *
     */
    public function testApiV1OrdersListGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersMovementDelete
     *
     * Delete an Order.
     *
     */
    public function testApiV1OrdersMovementDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersMovementPatch
     *
     * Updating an Order.
     *
     */
    public function testApiV1OrdersMovementPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersMovementPost
     *
     * Creating an Order.
     *
     */
    public function testApiV1OrdersMovementPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersPatch
     *
     * Updating an Order.
     *
     */
    public function testApiV1OrdersPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1OrdersPost
     *
     * Creating an Order.
     *
     */
    public function testApiV1OrdersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
