<?php
/**
 * PromotionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IM.Core.Api.Radix
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.39.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Radix\Test\Api;

use \OpenAPI\Client\Radix\Configuration;
use \OpenAPI\Client\Radix\ApiException;
use \OpenAPI\Client\Radix\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PromotionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Radix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PromotionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1PromotionsCountGet
     *
     * Returns the count of promotions.
     *
     */
    public function testApiV1PromotionsCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsDelete
     *
     * Delete an promotion.
     *
     */
    public function testApiV1PromotionsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsGet
     *
     * Returns a list of promotions.
     *
     */
    public function testApiV1PromotionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsIdIdGet
     *
     * Returns a list of promotions with minimal data.
     *
     */
    public function testApiV1PromotionsIdIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsIdIdPricesGet
     *
     * Returns a list of prices with this promotion id.
     *
     */
    public function testApiV1PromotionsIdIdPricesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsListGet
     *
     * Returns the promotion with this ID.
     *
     */
    public function testApiV1PromotionsListGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsPatch
     *
     * Updating an promotion.
     *
     */
    public function testApiV1PromotionsPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PromotionsPost
     *
     * Creating an promotion.
     *
     */
    public function testApiV1PromotionsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
